export const LOAD_LAYOUT_SETTINGS = 'LOAD_LAYOUT_SETTINGS';
export const UPDATE_LAYOUT_SETTINGS = 'UPDATE_LAYOUT_SETTINGS';
export const EMS_LAYOUT_SETTINGS = 'EMS_LAYOUT_SETTINGS';
export const CAB_LAYOUT_SETTINGS = 'CAB_LAYOUT_SETTINGS';
export const WEAZEL_LAYOUT_SETTINGS = 'WEAZEL_LAYOUT_SETTINGS';
